### ISSUE TITLE
[ERROR] The entry point "electron" cannot be marked as external

### ISSUE THREAD

**Issue by c-harding** [electron-vite/electron-vite-react#132]
Hi, I am unable to initialise this template. Do you know what I can do to fix this?

I get the following error when initialising and running the project on macOS 13.2.1:

<img width="2048" alt="image" src="https://user-images.githubusercontent.com/8607022/227772417-52c2c7ab-95b1-4d94-a19a-6ecac8d9bf22.png">

```
✘ [ERROR] The entry point "electron" cannot be marked as external

1:23:59 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
error: The entry point "electron" cannot be marked as external
    at failureErrorWithLog (/Users/c.harding/Sites/electron-vite-project/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/c.harding/Sites/electron-vite-project/node_modules/esbuild/lib/main.js:1048:25
    at runOnEndCallbacks (/Users/c.harding/Sites/electron-vite-project/node_modules/esbuild/lib/main.js:1471:45)
    at buildResponseToResult (/Users/c.harding/Sites/electron-vite-project/node_modules/esbuild/lib/main.js:1046:7)
    at /Users/c.harding/Sites/electron-vite-project/node_modules/esbuild/lib/main.js:1058:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (/Users/c.harding/Sites/electron-vite-project/node_modules/esbuild/lib/main.js:1057:54)
    at handleRequest (/Users/c.harding/Sites/electron-vite-project/node_modules/esbuild/lib/main.js:723:19)
    at handleIncomingPacket (/Users/c.harding/Sites/electron-vite-project/node_modules/esbuild/lib/main.js:745:7)
    at Socket.readFromStdout (/Users/c.harding/Sites/electron-vite-project/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by rr69sport** [comment]
I just had the same error 👀

**Comment by caoxiemeihao** [comment]
Upgrade to `v0.13.9`

**Comment by c-harding** [comment]
@caoxiemeihao sorry, what I am I upgrading? Where do I specify the version number?

**Comment by caoxiemeihao** [comment]
Haha, you can pull the latest code now 😂

**Comment by rr69sport** [comment]
> Upgrade to `vite-plugin-electron-renderer@0.13.9`


It works perfectly! 😃
