### ISSUE TITLE
building a bundle app using electron-react-vite with loadFiles not webserver

### ISSUE THREAD

**Issue by meddany** [electron-vite/electron-vite-react#141]
I am trying to learn something new here. I am working on client app which uses Electron + react.

I used this github repo to start my project https://github.com/electron-vite/electron-vite-react

And since i am not ready yet to learn typescript, I added //@ts-nocheck to most of my .tsx files in order to avoid  ts warnings/errors till i become ready to learn TS.

My problem that I can not bundle my app to share with others.

in package.json :-

```
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build && electron-builder",
    "preview": "vite preview",
    "pree2e": "vite build --mode=test",
    "e2e": "playwright test"
  },
```

in my first landing electron window = *electron/windows/win_landing.ts*
I am loading the `index.html` 
```
mainWindow.loadURL(indexHtml, { hash: arg })
```

Then i run `npm run build`

whenever i try to launch the bundeled app which generated under dist/, i get 

```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
```

index.html:-

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Security-Policy" content="script-src 'self' 'unsafe-inline';" />
    <title>Orion</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./src/main.tsx" ></script>
  </body>
</html>

```

This error never show up when i use `mainWindow.loadURL('http://localhost:5173/app/landing')` in my win_landing.

I tried to change `<script type="module" src="./src/main.tsx" ></script>` in my index.html file to main.js, I receive this error 

`caught TypeError: Failed to resolve module specifier "react/jsx-runtime". Relative references must start with either "/", "./", or "../".`

I tried to change the name of my main react js script to index.js instead of index.tsx,
also tried to change to .mjs.

Also tried to add `        mimeTypes: {
          'ts': 'application/javascript',
          'tsx': 'application/javascript',
        }`
 to vite.config.ts

If you could help me to figure out what i am missing to build my app correctly i will be grateful.

Here is my github repo if you want to give a deeper look 

[GITHUB](https://github.com/meddany/orion-ui-client)

**Comment by Erasmus001** [comment]
Try to add this npm module "isDev" to check if its in dev-mode or prod-mode

If in dev mode, your function that loads the file should be like "window.loadURL("path/to/your/local/server")" and if in prod "window.loadFile("path/to/your/index-file")"

**Comment by Erasmus001** [comment]
> Try to add this npm module "isDev" to check if its in dev-mode or prod-mode
> 
> If in dev mode, your function that loads the file should be like "window.loadURL("path/to/your/local/server")" and if in prod "window.loadFile("path/to/your/index-file")"

Fixed this issue a long time ago, try if it works

**Comment by meddany** [comment]
i update my electron landing window with this :

```
process.env.DIST_ELECTRON = join(__dirname, '../')
process.env.DIST = join(process.env.DIST_ELECTRON, '../')
process.env.PUBLIC = process.env.VITE_DEV_SERVER_URL
  ? join(process.env.DIST_ELECTRON, '../public')
  : process.env.DIST

const indexHtml = join(process.env.DIST, 'index.html')

    var arg = ''
    if (process.env.VITE_DEV_SERVER_URL) {
      mainWindow.loadURL('http://localhost:5173/app/landing')
    } else {
      console.log(indexHtml)
      mainWindow.loadFile(indexHtml, { hash: arg })
    }

```

my index html 

`<script type="module" src="./src/main.ts" ></script>`

then i executed npm run build

this is the output :

```
PS E:\PC\orion ui ts\v2> npm run build

> Orion@2.2.0 build
> tsc && vite build && electron-builder

vite v4.2.1 building for production...
✓ 2172 modules transformed.
dist/index.html                                                      0.56 kB
dist/assets/nokiapureheadline_regular-webfont-cf1eab8a.woff2        22.14 kB
dist/assets/nokiapureheadline_ultralight-webfont-477509db.woff2     23.00 kB
dist/assets/nokiapureheadline_light-webfont-97d5cfce.woff2          23.54 kB
dist/assets/nokiapureheadline_extrabold-webfont-1a52d383.woff2      23.68 kB
dist/assets/nokiapuretext-regular-webfont-d2713333.woff2            24.29 kB
dist/assets/nokiapuretext-light-webfont-82f8a3cc.woff2              24.45 kB
dist/assets/nokiapureheadline_bold-webfont-8b6e74a9.woff2           24.60 kB
dist/assets/nokiapuretext-bold-webfont-f4d52e6d.woff2               24.74 kB
dist/assets/nokiapuretext-medium-webfont-a785f03b.woff2             25.87 kB
dist/assets/nokiapureheadline_regular-webfont-c700330a.woff         28.28 kB
dist/assets/logo-top-bar-e2104280.png                               28.32 kB
dist/assets/nokiapuretext-regular-webfont-fc977afa.woff             29.86 kB
dist/assets/nokiapuretext-light-webfont-abae7846.woff               30.14 kB
dist/assets/nokiapureheadline_ultralight-webfont-95171def.woff      30.23 kB
dist/assets/nokiapuretext-bold-webfont-acc26026.woff                30.58 kB
dist/assets/nokiapureheadline_light-webfont-f431fe87.woff           30.72 kB
dist/assets/nokiapureheadline_extrabold-webfont-c2ab804c.woff       31.46 kB
dist/assets/orionlogo-01d00864.png                                  31.77 kB
dist/assets/nokiapureheadline_bold-webfont-8a5a5012.woff            32.34 kB
dist/assets/nokiapuretext-medium-webfont-750e5ef6.woff              33.13 kB
dist/assets/rolling-a1156b02.gif                                    80.29 kB
dist/assets/index-5c8829c9.css                                     416.66 kB │ gzip:  62.33 kB
dist/assets/index-247bbe46.js                                    2,770.84 kB │ gzip: 744.54 kB

(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks       
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 37.28s
vite v4.2.1 building for production...
✓ 5 modules transformed.
dist-electron/main/index.js  3.81 kB │ gzip: 1.32 kB
✓ built in 99ms
vite v4.2.1 building for production...
✓ 1 modules transformed.
dist-electron/preload/index.js  1.60 kB │ gzip: 0.77 kB
✓ built in 27ms
  • electron-builder  version=23.6.0 os=10.0.19042
  • writing effective config  file=dist\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=24.1.2 appOutDir=dist\win-unpacked
  • building        target=nsis file=dist\Orion Setup 2.2.0.exe archs=x64 oneClick=true perMachine=false
  • building block map  blockMapFile=dist\Orion Setup 2.2.0.exe.blockmap
PS E:\PC\orion ui ts\v2> 
```

then i go to dist/ and launch my electron app, 

i see this error 

Failed to load resource: net::ERR_FILE_NOT_FOUND main.ts:!1

**Comment by RSS1102** [comment]
i get this error:
```
Error: The following dependencies are imported but could not be resolved:

  ag-grid-community/styles/ag-grid.css (imported by E:/GitHubDesktop/orion-ui-client/src/components/dataTable.js)
  ag-grid-community/styles/ag-theme-alpine.css (imported by E:/GitHubDesktop/orion-ui-client/src/components/dataTable.js)
  prop-types (imported by E:/GitHubDesktop/orion-ui-client/src/components/sp_FormEdit.js)

Are they installed?
    at file:///E:/GitHubDesktop/orion-ui-client/node_modules/.store/vite@4.3.3/node_modules/vite/dist/node/chunks/dep-a178814b.js:44144:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///E:/GitHubDesktop/orion-ui-client/node_modules/.store/vite@4.3.3/node_modules/vite/dist/node/chunks/dep-a178814b.js:43553:38

E:\GitHubDesktop\orion-ui-client\index.html
```
maybe your `src/components/**` have some error?

**Comment by SwapnilSoni1999** [comment]
Facing same problem can you tell what exactly could be the issue in components/ ?

**Comment by caoxiemeihao** [comment]
```json
{
  "scripts": {
    "dev": "vite"
  },
}
```

`npm run dev` does a lot of work behind the scenes, not just compiling `.tsx`, `.ts` into `.jsx`, `.js`.
For those just starting out with Electron, I recommend using [electron-quick-start](https://github.com/electron/electron-quick-start)

**Comment by SwapnilSoni1999** [comment]
I've been facing issue with blank page after compilation
I solved it with `MemoryRouter` 
You can either use `MemoryRouter` or `HashRouter` whatever you want
