### ISSUE TITLE
build error  require() of ES Module  http-proxy-agent/dist/agent.js not supported.

### ISSUE THREAD

**Issue by vanxv** [electron-vite/electron-vite-react#144]
Error [ERR_REQUIRE_ESM]: require() of ES Module /Volumes/math/120Code/aiinfo/aiinfo_react/release/2.0.0/mac/aiinfo.app/Contents/Resources/app/node_modules/@tootallnate/once/dist/index.js from /Volumes/math/120Code/aiinfo/aiinfo_react/release/2.0.0/mac/aiinfo.app/Contents/Resources/app/node_modules/http-proxy-agent/dist/agent.js not supported.
Instead change the require of index.js in /Volumes/math/120Code/aiinfo/aiinfo_react/release/2.0.0/mac/aiinfo.app/Contents/Resources/app/node_modules/http-proxy-agent/dist/agent.js to a dynamic import() which is available in all CommonJS modules.
at c._load (node:electron/js2c/asar_bundle:5:13343)
at Object.<anonymous> (/Volumes/math/120Code/aiinfo/aiinfo_react/release/2.0.0/mac/aiinfo.app/Contents/Resources/app/node_modules/http-proxy-agent/dist/agent.js:19:32)
at c._load (node:electron/js2c/asar_bundle:5:13343)
at Object.<anonymous> (/Volumes/math/120Code/aiinfo/aiinfo_react/release/2.0.0/mac/aiinfo.app/Contents/Resources/app/node_modules/http-proxy-agent/dist/index.js:5:33)
at c._load (node:electron/js2c/asar_bundle:5:13343)
at Object.<anonymous> (/Volumes/math/120Code/aiinfo/aiinfo_react/release/2.0.0/mac/aiinfo.app/Contents/Resources/app/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:49:44)
at c._load (node:electron/js2c/asar_bundle:5:13343)
at Object.<anonymous> (/Volumes/math/120Code/aiinfo/aiinfo_react/release/2.0.0/mac/aiinfo.app/Contents/Resources/app/node_modules/@puppeteer/browsers/lib/cjs/browser-data/chrome.js:23:23)
at c._load (node:electron/js2c/asar_bundle:5:13343)
at Object.<anonymous> (/Volumes/math/120Code/aiinfo/aiinfo_react/release/2.0.0/mac/aiinfo.app/Contents/Resources/app/node_modules/@puppeteer/browsers/lib/cjs/browser-data/browser-data.js:42:29)
at c._load (node:electron/js2c/asar_bundle:5:13343)
at Object.<anonymous> (/Volumes/math/120Code/aiinfo/aiinfo_react/release/2.0.0/mac/aiinfo.app/Contents/Resources/app/node_modules/@puppeteer/browsers/lib/cjs/launch.js:39:27)
at c._load (node:electron/js2c/asar_bundle:5:13343)
at Object.<anonymous> (/Volumes/math/120Code/aiinfo/aiinfo_react/release/2.0.0/mac/aiinfo.app/Contents/Resources/app/node_modules/@puppeteer/browsers/lib/cjs/main.js:19:19)
at c._load (node:electron/js2c/asar_bundle:5:13343)
at Object.<anonymous> (/Volumes/math/120Code/aiinfo/aiinfo_react/release/2.0.0/mac/aiinfo.app/Contents/Resources/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:24:20)
at c._load (node:electron/js2c/asar_bundle:5:13343)
at Object.<anonymous> (/Volumes/math/120Code/aiinfo/aiinfo_react/release/2.0.0/mac/aiinfo.app/Contents/Resources/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/node.js:32:14)
at c._load (node:electron/js2c/asar_bundle:5:13343)
at Object.<anonymous> (/Volumes/math/120Code/aiinfo/aiinfo_react/release/2.0.0/mac/aiinfo.app/Contents/Resources/app/node_modules/puppeteer-core/lib/cjs/puppeteer/puppeteer-core.js:35:14)
at c._load (node:electron/js2c/asar_bundle:5:13343)
at Module.<anonymous> (/Volumes/math/120Code/aiinfo/aiinfo_react/release/2.0.0/mac/aiinfo.app/Contents/Resources/app/dist/electron/main/index.js:1:210)
at c._load (node:electron/js2c/asar_bundle:5:13343)
at Object.<anonymous> (node:electron/js2c

**Comment by RSS1102** [comment]
maybe you should in your code?
```
import { xxx} from 'http-proxy-agent';
```
